name: ClientCore
version: '${version}'
main: net.danh.clientcore.ClientCore
api-version: '26.1.2'
load: POSTWORLD
authors: [ VoChiDanh ]
folia-supported: true
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    WorldGuard:
      load: BEFORE
      required: false
    MMOItems:
      load: BEFORE
      required: false
    MythicMobs:
      load: BEFORE
      required: false
    ModelEngine:
      load: BEFORE
      required: false
    FancyNpcs:
      load: BEFORE
      required: false
    Citizens:
      load: BEFORE
      required: false
    Oraxen:
      load: BEFORE
      required: false
    ItemsAdder:
      load: BEFORE
      required: false
    Nexo:
      load: BEFORE
      required: false
    CraftEngine:
      load: BEFORE
      required: false
permissions:
  clientcore.admin:
    default: op
  clientcore.luck:
    default: true
