title: ClientCore Documentation
description: Official Wiki and Documentation for the ClientCore Plugin.
remote_theme: just-the-docs/just-the-docs

color_scheme: dark

markdown: kramdown
plugins:
  - jekyll-seo-tag
